import pandas as pd
import numpy as np
import re
import os
from pathlib import Path, WindowsPath
from odf.opendocument import load
from odf.table import Table, TableRow, TableCell
from odf.namespaces import TABLENS

# Get list of _ptr and non _ptr files for easier searching
file_pattern = re.compile(r'_ptr\.asm$')
ptrfiles = [
        p for p in Path("./armips/text").iterdir()
        if p.is_file() and file_pattern.search(p.name)
    ]
strfiles = [
        p for p in Path("./armips/text").iterdir()
        if p.is_file() and not file_pattern.search(p.name)
    ]
#print(strfiles)

# Initialize text_newstrings.asm for new entries in the Individual Strings sheet
newstrings = open("armips/text/text_newstrings.asm", "w")
newstrings.write("; This file is autogenerated from new strings pulled from output.ods\n; and is refreshed every time the patch is tested.\n\n")

print("Inserting strings...")

# Open output.ods's Individual Strings sheet (s for Source)
s = pd.read_excel("output.ods", engine="odf", sheet_name="Individual Strings", header=None)

for i, row in s.iterrows():
    target_label = row[0] # Get the label for the string we're gonna insert
    label_source = None
    target_line_num = None
    for file in strfiles: # Iterate through all strfiles to find where label is defined
        if file == WindowsPath('armips/text/text_newstrings.asm'):
            continue
        with open(Path(file), "r") as f:
            for i, line in enumerate(f):
                if target_label in line:
                    label_source = file
                    target_line_num = i
                    #print("Found label " + row[0] + " at line " + str(target_line_num))
                    break
        if label_source:
            break
    if label_source != None: # We found a label from the original script dump, and we're replacing it
        with open(Path(file), "r") as f:
            data = f.readlines()
        data[target_line_num + 2] = ".string \"" + row[2] + "\"\n"
        with open(Path(file), "w") as f:
            f.writelines(data)
    else: # This is done for a new string
        newstrings.write(row[0] + ":\n.string: \"" + row[2] + "\"\n")
        
print("Done!")
print("Inserting labels...")
tables = ["dialogue1", "dialogue2", "dialogue3", "system", "itemonuse", "itemdescriptions", "battle"]
table_sheets = ["Dialogue 1", "Dialogue 2", "Dialogue 3", "System", "Item On Use", "Item Descriptions", "Battle"]
label_regex = re.compile(r'^of\:\=COM\.MICROSOFT\.XLOOKUP\(\"(.*)\"')
for i, sheet in enumerate(table_sheets):
    current_asm_line = 3 - 7
    s = load("output.ods")
    s = s.spreadsheet.getElementsByType(Table)[i + 1]
    with open("armips/text/text_" + tables[i] + "_ptr.asm", "r") as f:
        data = f.readlines()
    for x, row in enumerate(s.getElementsByType(TableRow)):
        if x % 2 == 0:
            current_asm_line += 7
        else:
            current_asm_line += 1
        #print(data[current_asm_line])
        cell = row.getElementsByType(TableCell)
        match = label_regex.match(cell[2].getAttribute("formula"))
        if match:
            data[current_asm_line] = ".word " + match.group(1) + "\n"
    with open("armips/text/text_" + tables[i] + "_ptr.asm", "w") as f:
        f.writelines(data)

print("Done!")









