; This file is autogenerated from new strings pulled from output.ods
; and is refreshed every time the patch is tested.

.org SpecialTextEnd

NewStringsStart:

uselesssword2:
.string "positive effects."
uselessrod2:
.string "to stone."

NewStringsEnd:
