; This file is autogenerated from new strings pulled from output.ods
; and is refreshed every time the patch is tested.

.org DefaultNameEnd

NewStringsStart:

knowanything2:
.string "anything, huh?"
keepclimbing2:
.string "the towers…"
escape2:
.string "escape the fight."
smoothtalk2:
.string "enemy."
unicorn2:
.string "summons a unicorn."
nanimono2:
.string "unknown entity."
odoridasu2:
.string "the enemy."
entrance2:
.string "make an entrance."
magic2:
.string "magic trick."
taste2:
.string "taste."
prayer2:
.string "unheard."
uselesssword2:
.string "positive effects."
uselessrod2:
.string "to stone."
strange2:
.string "strange."
resentment1:
.string "ｃ looks"

NewStringsEnd:
