; This file is autogenerated from new strings pulled from output.ods
; and is refreshed every time the patch is tested.

.org SpecialTextEnd

NewStringsStart:

escape2:
.string "escape the fight."
smoothtalk2:
.string "enemy."
unicorn2:
.string "summons a unicorn."
nanimono2:
.string "unknown entity."
odoridasu2:
.string "the enemy."
entrance2:
.string "make an entrance."
magic2:
.string "magic trick."
taste2:
.string "taste."
prayer2:
.string "make it."
uselesssword2:
.string "positive effects."
uselessrod2:
.string "to stone."

NewStringsEnd:
